name: tk-sync
on:
  push:
    paths: ['.tickets/**']
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: https://git.satsang.xyz/ramram/forgejo-sync@main
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
